name: lab_website
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - flask
  - pip:
      - langchain-community
      - langchain-ollama
      - faiss-cpu
      - pypdf
      - ollama
      - flask-cors