name: Deploy Eleventy Site

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set destination dir
        id: set-dir
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEST=dev" >> "$GITHUB_OUTPUT"
          else
            echo "DEST=." >> "$GITHUB_OUTPUT"
          fi

      - name: Build site with Eleventy
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            ELEVENTY_PATH_PREFIX="/dev/" npm run build
          else
            ELEVENTY_PATH_PREFIX="/" npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ${{ steps.set-dir.outputs.DEST }}